config/routes.rb
Rails.application.routes.draw do
  
    root to: 'pages#home'
    get 'about', to: 'pages#about'

    resources :articles

    get 'signup', to: 'users#new'
    resources :users, except: [:new]

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :categories, except: [:destroy]

end

app/models/Article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :user_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name 

end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { minimum: 3, maximum: 25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
        uniqueness: { case_sensitive: false },
        length: { maximum: 105 },
        format: { with: VALID_EMAIL_REGEX }

    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
      !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit
    end



    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)

        else
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfuly updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end

    end

    def show
    end

    def destroy
        @article.destroy
        flash[:success] = "Article was successfully deleted"
        redirect_to articles_path
    end



    private
        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end

    def require_same_user
        if current_user != @article.user and !current_user.admin?
          flash[:danger] = "You can only edit or delete your own article"
          redirect_to root_path
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end

    end

    def edit
       @category = Category.find(params[:id])
    end

    def update  
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Name was successfully updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private 
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? && !current_user.admin?)
            flash[:danger] = "Only administrators can perform that action"
            redirect_to categories_path
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in."
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end 
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the alpha blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit

    end

    def update
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else    
            render 'edit'
        end
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles have been deleted"
        redirect_to users_path
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    private def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end

    def require_admin
        if logged_in? && !current_user.admin?
            flash[:danger] = "Only admin users can perform that action"
            redirect_to root_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end


end

app/views/articles/_article.html.erb
<table>

<% obj.each do |article| %>

        <div class="col-sm-8 offset-sm-2 mt-3 mb-3">
            <div class="card">
                <div class="card-header">
                    <h2 align="center">Title: <%= article.title %></h2>
                </div>
                <div class="card-body text-left">
                    <p class="card-text">
                        <%= truncate(article.description, length: 100) %>
                        <div class="article-meta-details">
                            <small>
                                Created By: <%= article.user.username if article.user %>, 
                                <%= time_ago_in_words(article.created_at) %> ago, 
                                last updated: <%= time_ago_in_words(article.updated_at) %> ago
                                <% if article.categories.any? %>
                                    <p>Cagegories: <%= render article.categories %></p>
                                <% end %>
                            </small> 
                        </div>
                    </p>

                    <hr>

                    <div class="article-actions col-sm-10">
                        <%= link_to "View", article_path(article), class: "btn btn-sm btn-success" %> 
                        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                            <%= link_to "Edit", edit_article_path(article), class: "btn btn-sm btn-primary" %> 
                        <% end %>
                    </div>
                </div>
            </div>
        </div>


    <% end %>

    </table>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="container">
<%= form_for @article do |f| %>
  <div class="row form-group">
    <!-- <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label> -->
    <div class="col-sm text-right">
        <%= f.label :title, class: "col-form-label" %>
    </div>
    <div class="col-sm-8">
      <!-- <input type="email" class="form-control" id="inputEmail3"> -->
      <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
    </div>
    <div class="col-sm">
    </div>
  </div>
  <div class="row form-group">
    <!-- <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label> -->
    <div class="col-sm text-right">
        <%= f.label :description, class: "col-form-label" %>    
    </div>
    <div class="col-sm-8">
      <!-- <input type="password" class="form-control" id="inputPassword3"> -->
      <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
    </div>
    <div class="col-sm">
    </div>

  </div>
  <div class="row form-group">
    <!-- <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label> -->
    <div class="col-sm-2 col-form-label"></div>
     <div class="col-sm-10">
      <small>
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox ml-4 mr-2") + cb.text } %>
        <% end %>
      </small>
    </div>
    <div class="col-sm">
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2 col-form-label"></div>
    <div class="col-sm-10">
      <!-- <button type="submit" class="btn btn-primary">Sign in</button> -->
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>


<%= link_to "[ Cancel request and return to article listing ]", articles_path %>

<script>
  var options = [];

  $( '.dropdown-menu a' ).on( 'click', function( event ) {

     var $target = $( event.currentTarget ),
         val = $target.attr( 'data-value' ),
         $inp = $target.find( 'input' ),
         idx;

     if ( ( idx = options.indexOf( val ) ) > -1 ) {
        options.splice( idx, 1 );
        setTimeout( function() { $inp.prop( 'checked', false ) }, 0);
     } else {
        options.push( val );
        setTimeout( function() { $inp.prop( 'checked', true ) }, 0);
     }

     $( event.target ).blur();
        
     console.log( options );
     return false;
  });
</script>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>List of all Articles</h1>
<p><%= link_to "Create New Article", new_article_path %></p>

<div class="row">
    <div class="mx-auto">
        <%= will_paginate %>
    </div>
</div>
    <%= render 'article', obj: @articles %>

<div class="row">
    <div class="mx-auto">
        <%= will_paginate %>
    </div>
</div>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="col-sm-8 offset-sm-2 ">
    <div class="card">
        <div class="card-header">
            <h2 align="center">Title: <%= @article.title %></h2>
        </div>
        <div class="card-body text-left">
            <% if @article.user %> 
            <ul class="listing center">
                <li><small class="center">Created By: </small></li>
                <li>
                    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                </li>
                <li class="article-title">
                    <%= link_to @article.user.username, user_path(@article.user) %>
                </li>
                <li>
                    <small>
                        <%= pluralize(@article.user.articles.count, "article") %>
                    </small>
                </li>
            </ul>
            <% end %>
            <h4>Description:</h4>
            <p class="card-text"><%= @article.description %></p>
            <% if @article.categories.any? %>
                <small><p>Categories: <%= render @article.categories %></p></small>
            <% end %>
            <hr>
            <div class="article-actions col-sm-10">
                <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-sm btn-primary" %> 
                    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-sm btn-danger" %>
                <% end %>
                <%= link_to "Article List", articles_path, class: "btn btn-sm btn-secondary" %>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-primary ml-1" %>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

<div class="container">
<%= form_for @category do |f| %>
  <div class="row form-group">
    <!-- <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label> -->
    <div class="col-sm text-right">
        <%= f.label :name, class: "col-form-label" %>
    </div>
    <div class="col-sm-8">
      <!-- <input type="email" class="form-control" id="inputEmail3"> -->
      <%= f.text_field :name, class: "form-control", placeholder: "Category name" %>
    </div>
    <div class="col-sm">
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2 col-form-label"></div>
    <div class="col-sm-10">
      <!-- <button type="submit" class="btn btn-primary">Sign in</button> -->
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>


<%= link_to "[ Cancel request and return to article listing ]", articles_path %>

app/views/categories/edit.html.erb
<h1 align="cetner">Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>

<div class="row">
    <div class="mx-auto">
        <%= will_paginate %>
    </div>
</div>


<% @categories.each do |category| %>
   <ul class="listing">
       <div class="row">
           <div class="card col-md-4 offset-md-4">
               <li class="article-title">
                   <%= link_to "#{category.name}", category_path(category) %>
               </li>
               <li>
                 <small>
                   <%= pluralize(category.articles.count, 'article') %>
                 </small>
               </li>
           </div>
       </div>
   </ul> 
<% end %>

<div class="row">
    <div class="mx-auto">
        <%= will_paginate %>
    </div>
</div>

app/views/categories/new.html.erb
<h1 align="cetner">Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= "Category: " + @category.name %></h1>

<div class="row">
        
    <div class="mx-auto">
        <% if  logged_in? && current_user.admin? %>
            <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-primary btn-sm" %>
        <% end %>
        <%= will_paginate @category_articles %>
    </div>
</div>
    <%= render 'articles/article', obj: @category_articles %>

<div class="row">
    <div class="mx-auto">
        <%= will_paginate @category_articles%>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="#">Goat LLC</a>
        </small>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="container">
        <div class="col-sm-10 mt-4 ml-auto mr-auto">
            <div class='alert alert-<%= "#{name}" %> alert-dismissible fade show' role="alert">
                <%= msg %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand logo" href="">Alpha Blog</a> -->
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Menu
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
  <!--           <a class="dropdown-item" href="#">Action</a> -->
            <%= link_to "Create New Article", new_article_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Users", users_path, class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
  <!--           <a class="dropdown-item" href="#">Action</a> -->
            <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category), class: "dropdown-item"  %>
            <% end %>
            <div class="dropdown-divider"></div>
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Create Category", new_category_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if logged_in? && current_user.admin? %>
          <li class="new-item my-auto ml-5">
            <small class="alert alert-primary">Admin</small>
          </li>
        <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    
    <div class="container center body">
      <%= yield %>  
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About Page</h1>
    <%= link_to "Home", root_path %>
</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="display-4">Alpha Blog</h1>

  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>

  <%= link_to "All Articles", articles_path, class: "btn btn-primary btn-lg btn-xlg" %>
  <%= link_to "Sign up", signup_path, class: "btn btn-secondary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-danger alert-dismissible fade show text-left " role="alert">
                <%= pluralize(obj.errors.count, "error") %>
                prevented this article from saving:
                <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<div class="container">
<%= form_for @user do |f| %>
  <div class="row form-group">
    <!-- <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label> -->
    <div class="col-sm text-right">
        <%= f.label :username, class: "col-form-label" %>
    </div>
    <div class="col-sm-8">
      <!-- <input type="email" class="form-control" id="inputEmail3"> -->
      <%= f.text_field :username, class: "form-control", placeholder: "Enter username" %>
    </div>
    <div class="col-sm">
    </div>
  </div>
  <div class="row form-group">
    <!-- <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label> -->
    <div class="col-sm text-right">
        <%= f.label :email, class: "col-form-label" %>    
    </div>
    <div class="col-sm-8">
      <!-- <input type="password" class="form-control" id="inputPassword3"> -->
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>
    <div class="col-sm">
    </div>

  </div>
  <div class="row form-group">
    <!-- <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label> -->
    <div class="col-sm text-right">
        <%= f.label :password, class: "col-form-label" %>    
    </div>
    <div class="col-sm-8">
      <!-- <input type="password" class="form-control" id="inputPassword3"> -->
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
    <div class="col-sm">
    </div>

  </div>
  <div class="form-group row">
    <div class="col-sm-2 col-form-label"></div>
    <div class="col-sm-10">
      <!-- <button type="submit" class="btn btn-primary">Sign in</button> -->
      <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary") %>
    </div>
  </div>
<% end %>
</div>


<%= link_to "[ Cancel request and return to article listing ]", articles_path %>

app/views/users/edit.html.erb
<h1 align="center">Edit your Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div class="row">
    <div class="mx-auto">
        <%= will_paginate %>
    </div>
</div>
<% @users.each do |user| %>
    <ul class="listing">
        <div class="row">
            <div class="card user-list col-md-4 offset-md-4">
                <div class="card-body">
                    <li>
                        <%= link_to gravatar_for(user), user_path(user) %>
                    </li>
                    <li class="article-title">
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li>
                        <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
                    </li>
                    <% if logged_in? and current_user.admin? %>
                        <li><%= link_to "Delete User", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user and all articles?" } %></li>
                    <% end %>
                </div>
            </div>
        </div>
    </ul>
<% end %>
<div class="row">
    <div class="mx-auto">
        <%= will_paginate %>
    </div>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
    <div class="col-md-4 offset-md-4 center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="row">
    <div class="mx-auto">
        <%= will_paginate @user_articles %>
    </div>
</div>

<%= render 'articles/article', obj: @user_articles %>

<div class="row">
    <div class="mx-auto">
        <%= will_paginate @user_articles %>
    </div>
</div>